name: MoeAfk
main: cn.whiteg.moeAfk.MoeAfk
version: 1.1
author: MoeWhite
depend: [MMOCore]
softdepend: []
api-version: 1.13
commands:
  moeafk:
    description: The is MoeAfk
    aliases: ['ma']
  afk:
    description: Afk Command